# Site settings
title: Profile
description: "I like Hip-Hop"
url:  "https://leonardo.github.io/profile" # Actual base url of the website
baseurl: "/"           # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Leonardo"
  email: "ch01224.park@samsung.com"
permalink: /:year/:month/:day/:title:output_ext

#Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

#Pagination
paginate: 3
paginate_path: "/page:num/"

#SEO
instagram:
  username: leonardo.park
  card : summary
logo: /assets/img/Leonardo.jpg
social:
  links: #List your social links here
    - https://github.com/Leonardo0912
    - https://www.instagram.com/leonardo.park/
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
lang: en_US

#Highlighter
kramdown:
  input:          GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

#Sass
sass:
  style: compressed
  sourcemap: never
  
#add  
theme: jekyll-yamt
